### ISSUE TITLE
Feature request: Folder note options instead of README.md

### ISSUE THREAD

**Issue by TheRealPJC** [quanru/obsidian-periodic-para#49]
Currently every PARA folder requires a README.md. It would be useful if the user had the option to use a [folder note](https://github.com/LostPaul/obsidian-folder-notes) instead. (This is just a file with the same name as the directory). 

This would help users who are used to using folder notes as their "top level" file. It would also allow extra functionality to be included e.g [Waypoints](https://github.com/IdreesInc/Waypoint)) can only be added to folder notes.

**Comment by quanru** [comment]
Good idea, I will think about it~
Thanks

**Comment by quanru** [comment]
I can make the index file support the same name as the folder, but this will not be the default option because it will cause people who do not use the Folder note plugin to generate a file with a long file name.

In other words, when you need it, you need to manually modify the file name yourself when creating PARA notes. Do you think this is feasible?

**Comment by quanru** [comment]
Update the periodic para plugin to version 1.11.0, now support the index file with the same name as the folder

@TheRealPJC

**Comment by quanru** [comment]
https://obsidian-life-os.netlify.app/news/apr-changelog.html

@TheRealPJC now support advance setting
